version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: superhero_postgres
    restart: always
    environment:
      POSTGRES_USER: superhero_user
      POSTGRES_PASSWORD: superhero_password
      POSTGRES_DB: superhero_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: superhero_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@superhero.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: