services:
  # PostgreSQL Database
  - type: pserv
    name: superhero-database
    env: postgresql
    plan: free

  # Backend API Service
  - type: web
    name: superhero-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm ci
      npx prisma generate
      npm run build
    startCommand: |
      cd backend
      npx prisma db push --accept-data-loss
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: superhero-database
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: superhero-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: superhero-backend
          property: host
          suffix: /api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
